function Hd = getElliptic
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.9 and DSP System Toolbox 9.11.
% Generated on: 10-Nov-2021 23:10:35

Fpass = 2500;   % Passband Frequency
Fstop = 4000;   % Stopband Frequency
Apass = 3;      % Passband Ripple (dB)
Astop = 92;     % Stopband Attenuation (dB)
Fs    = 44100;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'ellip', ...
    'MatchExactly', 'both', ...
    'SystemObject', true);


